# Generated by Django 5.0.4 on 2024-04-10 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='monedasJuego',
            new_name='monedas_juego',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='numeroCelular',
            new_name='numero_celular',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='numeroEmpleado',
            new_name='numero_empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='puntosJuego',
            new_name='puntos_juego',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='puntosTrabajo',
            new_name='puntos_trabajo',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='tiradasJuego',
            new_name='tiradas_juego',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='nombreSucursal',
            new_name='nombre_sucursal',
        ),
        migrations.AlterUniqueTogether(
            name='empleadopersonaje',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fotoPerfil',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='archivoFoto',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='fechaAsignacion',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='fechaAtendido',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='fechaReporte',
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='empleadopersonaje',
            name='en_uso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foto',
            name='archivo_foto',
            field=models.ImageField(default='fotos/default.jpg', upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_atendido',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_reporte',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='reportes.roles'),
        ),
        migrations.AlterField(
            model_name='estatus',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Verificado', 'Verificado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='asignador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_asignador', to='reportes.empleado'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='reportes.foto'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='promotor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_promotor', to='reportes.empleado'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='reportador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_reportador', to='reportes.empleado'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='reportes.estatus'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='reportes.sucursal'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='rol',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='empleadopersonaje',
            constraint=models.UniqueConstraint(fields=('empleado', 'personaje'), name='empleado_personaje_unique'),
        ),
        migrations.RemoveField(
            model_name='empleadopersonaje',
            name='enUso',
        ),
    ]
